def Title():
    print()
    print()
    print('                  ------|||||--|||||------')
    print('                  |                      |')
    print('                  |  Instance  Override  |')
    print('                  |                      |')
    print('                  ------|||||--|||||------')
    print()
    print()
    print("        (DARKNESS SURROUNDS YOU...NO LIGHT IS SIGHT!)")
    print()
    print("                     ------------------              ")
    print()
    print('                   ... Where...am...I?')
    print('  "HEEEELLLLLOOOOO!!!" Hmph, I have no idea what is going on...')
    print()
    print()
    print("            You know something isn't quite right.")